-- Radio Catalogue data
-- Auto-generated by rebuild_data_sql.py
PRAGMA foreign_keys = ON;

INSERT INTO artists (name, alias) VALUES ('Charli XCX', NULL);
INSERT INTO artists (name, alias) VALUES ('No Doubt', NULL);
INSERT INTO artists (name, alias) VALUES ('Buju Banton', NULL);
INSERT INTO artists (name, alias) VALUES ('Neon Indian', NULL);
INSERT INTO artists (name, alias) VALUES ('Classixxx', NULL);
INSERT INTO artists (name, alias) VALUES ('Nancy Whang', NULL);
INSERT INTO artists (name, alias) VALUES ('Björk', 'Bj??rk');
INSERT INTO artists (name, alias) VALUES ('Eric B. & Rakim', NULL);
INSERT INTO artists (name, alias) VALUES ('4minute', NULL);
INSERT INTO artists (name, alias) VALUES ('Perturbator', NULL);
INSERT INTO artists (name, alias) VALUES ('Cheryl Lynn', NULL);
INSERT INTO artists (name, alias) VALUES ('Britney Spears', NULL);
INSERT INTO artists (name, alias) VALUES ('The Brothers Johnson', NULL);
INSERT INTO artists (name, alias) VALUES ('ADULT.', NULL);
INSERT INTO artists (name, alias) VALUES ('Trang Pháp', 'Trang Ph??p');
INSERT INTO artists (name, alias) VALUES ('Nadine Coyle', NULL);
INSERT INTO artists (name, alias) VALUES ('5sta Family', NULL);
INSERT INTO artists (name, alias) VALUES ('Adrian Lux', NULL);
INSERT INTO artists (name, alias) VALUES ('Rebecca & Fiona', NULL);
INSERT INTO artists (name, alias) VALUES ('Luna', NULL);
INSERT INTO artists (name, alias) VALUES ('Miss Kittin', NULL);
INSERT INTO artists (name, alias) VALUES ('Xeno & Oaklander', NULL);
INSERT INTO artists (name, alias) VALUES ('2ne1', NULL);
INSERT INTO artists (name, alias) VALUES ('Afterschool', NULL);
INSERT INTO artists (name, alias) VALUES ('Yazoo', NULL);
INSERT INTO artists (name, alias) VALUES ('Girls Aloud', NULL);
INSERT INTO artists (name, alias) VALUES ('Covenant', NULL);
INSERT INTO artists (name, alias) VALUES ('Monatik', NULL);
INSERT INTO artists (name, alias) VALUES ('Dorofeeva', NULL);
INSERT INTO artists (name, alias) VALUES ('OTOY', NULL);
INSERT INTO artists (name, alias) VALUES ('Kard', NULL);
INSERT INTO artists (name, alias) VALUES ('Bronski Beat', NULL);
INSERT INTO artists (name, alias) VALUES ('Sneaker Pimps', NULL);
INSERT INTO artists (name, alias) VALUES ('Um Jung Hwa', NULL);
INSERT INTO artists (name, alias) VALUES ('HyunA', NULL);
INSERT INTO artists (name, alias) VALUES ('CHANGMO', NULL);
INSERT INTO artists (name, alias) VALUES ('Zapp', NULL);
INSERT INTO artists (name, alias) VALUES ('MC Breed', NULL);
INSERT INTO artists (name, alias) VALUES ('DFC', NULL);
INSERT INTO artists (name, alias) VALUES ('Chicago', NULL);
INSERT INTO artists (name, alias) VALUES ('Never Dull', NULL);
INSERT INTO artists (name, alias) VALUES ('Crystal Waters', NULL);
INSERT INTO artists (name, alias) VALUES ('The Isley Brothers', NULL);
INSERT INTO artists (name, alias) VALUES ('Ice Cube', NULL);
INSERT INTO artists (name, alias) VALUES ('Chaka Khan', NULL);
INSERT INTO artists (name, alias) VALUES ('Stardust', NULL);
INSERT INTO artists (name, alias) VALUES ('Hikaru Utada', 'Utada Hikaru');
INSERT INTO artists (name, alias) VALUES ('宇多田ヒカル', 'Hikaru Utada');

INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Nuclear Seasons', 'UK', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('New', 'USA', 'Alternative Rock', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Murderer', 'Jamaica', 'Reggae', 'English', 'Pol', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Change of Coast', 'USA', 'Soundtrack', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('All You''re Waiting For (feat. Nancy Whang)', 'USA', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Bachelorette', 'Iceland', 'Orchestral Pop', 'English', 'Sy', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Hunter', 'Iceland', 'Symphonic Pop', 'English', 'Sy', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Move the Crowd', 'USA', 'Hip-hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Eric B. is President', 'USA', 'Hip-hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('What''s Your Name?', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Future Club', 'USA', 'Electronic', 'none', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Got to Be Real', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Scary', 'Japan', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Strawberry Letter 23', 'USA', 'Psychedelic soul', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Hand to Phone (Cordless Mix)', 'USA', 'Electronic', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Lựa Chọn', 'Vietnam', 'Viet pop', 'Vietnamese', 'Viet', 'Lựa Chọn');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Chained', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Insatiable', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Put Your Hands Up', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Runnin''', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Буду с тобой', 'Russia', 'Pop', 'Russian', 'R/U', 'Budu s toboy');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Boy (Hardwell Remix) (feat. Rebecca & Fiona)', 'USA', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Free Somebody', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Keep on Doin''', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Bassline', 'France', 'Electropop', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rendez-Vous d''Or', 'USA', 'Dark wave', 'French', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Werke', 'USA', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Insomnia', 'USA', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('난 바빠', 'Korea', 'Kpop', 'Korean', 'K', 'Nan bappa');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Eyeline', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Situation', 'UK', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('It''s Magic', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Girl Overboard', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('What You Crying For', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Memory of You', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('How''s This?', 'Korea', 'Korean Trap', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Stalker', 'Sweden', 'Industrial', 'English', 'Industrial', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Vitamin D', 'Ukraine', 'Pop', 'Russian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Выходной', 'Ukraine', 'Pop', 'Russian', 'R/U', 'Vykhodnoy');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Глубоко...', 'Ukraine', 'Pop', 'Russian', 'R/U', 'Gluboko...');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('If you know what I mean', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('I.D.', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rumor', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Smalltown Boy', 'UK', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Tesko Suicide', 'UK', 'Alt dance', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Invitation', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('RSVP (feat. CHANGMO)', 'Korea', 'Kpop', 'Korean', 'Pair', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('More Bounce to the Ounce', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Ain''t No Future in Yo'' Frontin''', 'USA', 'G-funk', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Street Player', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('In My Mind (feat. Crystal Waters)', 'USA', 'House', 'Engish', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Footsteps in the Dark, Pts. 1 & 2', 'USA', 'R&B', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('It Was a Good Day', 'USA', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Fate', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Music Sounds Better with You', 'France', 'House', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Colors', 'Japan', 'Synthpop', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('テイク５', 'Japan', 'Dance pop', 'Japanese', 'J', 'Take 5');

INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (1, 1, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (2, 2, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (3, 3, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (4, 4, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (5, 5, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (5, 6, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (6, 7, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (7, 7, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (8, 8, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (9, 8, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (10, 9, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (11, 10, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (12, 11, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (13, 12, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (14, 13, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (15, 14, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (16, 15, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (17, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (18, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (19, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (20, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (21, 17, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (22, 18, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (22, 19, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (23, 20, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (24, 20, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (25, 21, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (26, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (27, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (28, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (29, 23, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (30, 24, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (31, 25, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (32, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (33, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (34, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (35, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (36, 36, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (37, 28, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (38, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (39, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (40, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (40, 30, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (41, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (41, 30, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (42, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (42, 31, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (43, 32, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (44, 33, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (45, 34, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (46, 35, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (47, 36, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (47, 37, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (48, 38, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (49, 39, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (49, 40, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (50, 41, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (51, 42, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (51, 43, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (52, 44, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (53, 45, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (54, 46, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (55, 47, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (56, 48, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (57, 49, 'primary');

-- [2026-03-31] 嘘みたいな (I Love You) — 宇多田ヒカル
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('嘘みたいな (I Love You)', 'Japan', 'uso mitaina  (I Love You )', 'Pop', 286, 'Japanese', 'J');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '嘘みたいな (I Love You)'
)
AND a.name = '宇多田ヒカル';

-- [2026-03-31] Synrise — Goose
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Synrise', 'UK', NULL, 'Electronic', 332, 'n/a', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Goose', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Synrise'
)
AND a.name = 'Goose';

-- [2026-03-31] All Night Long — Mary Jane Girls
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('All Night Long', 'USA', NULL, 'Funk', 334, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Mary Jane Girls', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'All Night Long'
)
AND a.name = 'Mary Jane Girls';

-- [2026-03-31] Buffalo Stance — Neneh Cherry
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Buffalo Stance', 'UK', NULL, 'Hip hop', 342, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Neneh Cherry', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Buffalo Stance'
)
AND a.name = 'Neneh Cherry';

-- [2026-03-31] Move On Up (Single Edit) — Curtis Mayfield
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Move On Up (Single Edit)', 'USA', NULL, 'Progressive soul', 173, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Curtis Mayfield', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Move On Up (Single Edit)'
)
AND a.name = 'Curtis Mayfield';

-- [2026-03-31] We're Rocking The Planet — Hashim
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('We''re Rocking The Planet', 'USA', NULL, 'Electro', 346, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Hashim', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'We''re Rocking The Planet'
)
AND a.name = 'Hashim';

-- [2026-03-31] Al-Naafiysh (The Soul) — Hashim
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Al-Naafiysh (The Soul)', 'USA', NULL, 'Electro', 333, NULL, 'Ox');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Al-Naafiysh (The Soul)'
)
AND a.name = 'Hashim';

-- [2026-03-31] Sucker M.C.'s (Krush-Groove 1) — Run-D.M.C.
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Sucker M.C.''s (Krush-Groove 1)', 'USA', NULL, 'Hip hop', 189, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Run-D.M.C.', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sucker M.C.''s (Krush-Groove 1)'
)
AND a.name = 'Run-D.M.C.';

-- [2026-03-31] Sponji Reggae — Black Uhuru
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Sponji Reggae', 'Jamaica', NULL, 'Roots reggae', 293, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('Black Uhuru', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sponji Reggae'
)
AND a.name = 'Black Uhuru';

-- [2026-03-31] Columbus - 2002 Remastered Version — Burning Spear
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Columbus - 2002 Remastered Version', 'Jamaica', NULL, 'Roots reggae', 217, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('Burning Spear', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Columbus - 2002 Remastered Version'
)
AND a.name = 'Burning Spear';

-- [2026-03-31] Zungguzungguguzungguzeng — Yellowman
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Zungguzungguguzungguzeng', 'Jamaica', NULL, 'Dancehall', 387, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('Yellowman', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Zungguzungguguzungguzeng'
)
AND a.name = 'Yellowman';

-- [2026-03-31] Nobody Move Nobody Get Hurt — Yellowman
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Nobody Move Nobody Get Hurt', 'Jamaica', NULL, 'Dancehall', 223, 'English', 'Reggae');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Nobody Move Nobody Get Hurt'
)
AND a.name = 'Yellowman';

-- [2026-03-31] Funky Worm — Ohio Players
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Funky Worm', 'USA', NULL, 'Funk', 161, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Ohio Players', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Funky Worm'
)
AND a.name = 'Ohio Players';

-- [2026-03-31] Skin Tight — Ohio Players
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Skin Tight', 'USA', NULL, 'Funk', 474, 'English', 'Cx');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Skin Tight'
)
AND a.name = 'Ohio Players';

-- [2026-03-31] Street Player — Chicago

-- [2026-03-31] FILTH IN THE BEAUTY — the GazettE
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('FILTH IN THE BEAUTY', 'Japan', NULL, 'Visual Kei', 251, 'Japanese', 'J');
INSERT INTO artists (name, alias) VALUES ('the GazettE', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'FILTH IN THE BEAUTY'
)
AND a.name = 'the GazettE';

-- [2026-03-31] Give Up The Funk (Tear The Roof Off The Sucker) — Parliament
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Give Up The Funk (Tear The Roof Off The Sucker)', 'USA', NULL, 'Funk', 348, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Parliament', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Give Up The Funk (Tear The Roof Off The Sucker)'
)
AND a.name = 'Parliament';

-- [2026-03-31] Heliosphan — Aphex Twin
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Heliosphan', 'UK', NULL, 'Ambient', 296, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('Aphex Twin', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Heliosphan'
)
AND a.name = 'Aphex Twin';

-- [2026-03-31] He's the Greatest Dancer — Sister Sledge
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('He''s the Greatest Dancer', 'USA', NULL, 'Disco', 376, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Sister Sledge', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'He''s the Greatest Dancer'
)
AND a.name = 'Sister Sledge';

-- [2026-03-31] Get Off — Foxy
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Get Off', 'USA', NULL, 'Disco', 244, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Foxy', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Get Off'
)
AND a.name = 'Foxy';

-- [2026-03-31] Likey — TWICE
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Likey', 'Korea', NULL, 'Kpop', 207, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('TWICE', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Likey'
)
AND a.name = 'TWICE';

-- [2026-03-31] CHERRY — ITZY
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('CHERRY', 'Korea', NULL, 'Kpop', 190, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('ITZY', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'CHERRY'
)
AND a.name = 'ITZY';

-- [2026-03-31] HIP — MAMAMOO
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('HIP', 'Korea', NULL, 'Kpop', 195, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('MAMAMOO', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'HIP'
)
AND a.name = 'MAMAMOO';

-- [2026-03-31] I Can Make You Dance — Zapp
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I Can Make You Dance', 'USA', NULL, 'Disco', 239, 'English', 'Ox');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I Can Make You Dance'
)
AND a.name = 'Zapp';

-- [2026-03-31] Good Times — CHIC
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Good Times', 'USA', NULL, 'Disco', 495, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('CHIC', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Good Times'
)
AND a.name = 'CHIC';

-- [2026-03-31] Natty Rebel — U-Roy
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Natty Rebel', 'USA', NULL, 'Dub', 204, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('U-Roy', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Natty Rebel'
)
AND a.name = 'U-Roy';

-- [2026-04-01] Moonlight Romance — Amazulu
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Moonlight Romance', 'UK', NULL, 'Soul', 211, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('Amazulu', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Moonlight Romance'
)
AND a.name = 'Amazulu';

-- [2026-04-01] Bright Lights (Netsky Remix) — Die & Interface, William Cartwright
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Bright Lights (Netsky Remix)', 'UK', NULL, 'Electronic', 290, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Die & Interface', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Bright Lights (Netsky Remix)'
)
AND a.name = 'Die & Interface';
INSERT INTO artists (name, alias) VALUES ('William Cartwright', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Bright Lights (Netsky Remix)'
)
AND a.name = 'William Cartwright';
UPDATE songs SET title = 'Bright Lights (Netsky Remix) (feat. William Cartwright)' WHERE title = 'Bright Lights (Netsky Remix)';

-- [2026-04-01] Big Brother UK TV Theme (Vocal Mix - Radio Edit) — ElementFour
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Big Brother UK TV Theme (Vocal Mix - Radio Edit)', 'UK', NULL, 'Trance', 200, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('ElementFour', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Big Brother UK TV Theme (Vocal Mix - Radio Edit)'
)
AND a.name = 'ElementFour';

-- [2026-04-01] セニョール セニョーラ セニョリータ — MIYAVI
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('セニョール セニョーラ セニョリータ', 'Japan', 'senyooru   senyoora   senyoriita', 'Pop', 263, 'Japanese', 'J');
INSERT INTO artists (name, alias) VALUES ('MIYAVI', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'セニョール セニョーラ セニョリータ'
)
AND a.name = 'MIYAVI';

-- [2026-04-01] MIЯROR — D'espairsRay
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('MIЯROR', 'Japan', 'MIJaROR', 'Visual kei', 250, 'Japanese', 'J');
INSERT INTO artists (name, alias) VALUES ('D''espairsRay', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'MIЯROR'
)
AND a.name = 'D''espairsRay';

-- [2026-04-01] Lost Scene — D'espairsRay
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Lost Scene', 'Japan', NULL, 'Visual kei', 268, 'Japanese', 'J');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lost Scene'
)
AND a.name = 'D''espairsRay';

-- [2026-04-01] Tu Sicaria — Ms Nina, Beauty Brain
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Tu Sicaria', 'Spain', NULL, 'Perreo', 147, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Ms Nina', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Tu Sicaria'
)
AND a.name = 'Ms Nina';
INSERT INTO artists (name, alias) VALUES ('Beauty Brain', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Tu Sicaria'
)
AND a.name = 'Beauty Brain';

-- [2026-04-01] 홀리가든 — 비디오로즈
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('홀리가든', 'Korea', 'holligadeun', 'Synth pop', 145, 'English', 'K');
INSERT INTO artists (name, alias) VALUES ('비디오로즈', 'bidi-olojeu');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '홀리가든'
)
AND a.name = '비디오로즈';

-- [2026-04-01] Afterglow — FAKY
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Afterglow', 'Japan', NULL, 'Jpop', 187, 'Japanese', 'J');
INSERT INTO artists (name, alias) VALUES ('FAKY', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Afterglow'
)
AND a.name = 'FAKY';

-- [2026-04-01] В ТЕМНОТЕ ТАНЦУЙ — ЯАVЬ
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('В ТЕМНОТЕ ТАНЦУЙ', 'Russia', 'V TEMNOTE TANTsUJ', 'Pop', 240, 'Russian', 'R/U');
INSERT INTO artists (name, alias) VALUES ('ЯАVЬ', 'JaAV''');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'В ТЕМНОТЕ ТАНЦУЙ'
)
AND a.name = 'ЯАVЬ';

-- [2026-04-01] Taboo Tears You Up — IOSYS
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Taboo Tears You Up', 'Japan', NULL, 'Touhou', 218, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('IOSYS', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Taboo Tears You Up'
)
AND a.name = 'IOSYS';

-- [2026-04-01] 이브의 경고 — 박미경
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('이브의 경고', 'Korea', 'ibeu-ui gyeonggo', 'Dance ballad', 252, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('박미경', 'bagmigyeong');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '이브의 경고'
)
AND a.name = '박미경';

-- [2026-04-01] Abracadabra — Brown Eyed Girls
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Abracadabra', 'Korea', NULL, 'Kpop', 184, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('Brown Eyed Girls', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Abracadabra'
)
AND a.name = 'Brown Eyed Girls';

-- [2026-04-01] Rumors — Lindsay Lohan
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Rumors', 'USA', NULL, 'Pop', 196, 'English', 'cringe');
INSERT INTO artists (name, alias) VALUES ('Lindsay Lohan', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Rumors'
)
AND a.name = 'Lindsay Lohan';

-- [2026-04-01] With Love — Hillary Duff
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('With Love', 'USA', NULL, 'Pop', 181, 'English', 'cringe');
INSERT INTO artists (name, alias) VALUES ('Hillary Duff', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'With Love'
)
AND a.name = 'Hillary Duff';

-- [2026-04-01] Boogie Shoes — KC & The Sunshine Band
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Boogie Shoes', 'USA', NULL, 'Funk', 132, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('KC & The Sunshine Band', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Boogie Shoes'
)
AND a.name = 'KC & The Sunshine Band';

-- [2026-04-01] 잘못된 만남 — 김건모
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('잘못된 만남', 'Korea', 'jalmosdoen mannam', 'Kpop', 258, 'Korean', 'K/Ox');
INSERT INTO artists (name, alias) VALUES ('김건모', 'gimgeonmo');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '잘못된 만남'
)
AND a.name = '김건모';

-- [2026-04-01] Outside Castle (The Castle Outsiders) — 에쵸티
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Outside Castle (The Castle Outsiders)', 'Korea', NULL, 'Kpop', 326, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('에쵸티', 'echyoti');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Outside Castle (The Castle Outsiders)'
)
AND a.name = '에쵸티';

-- [2026-04-01] Here I Am (Come and Take Me) — Al Green
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Here I Am (Come and Take Me)', 'USA', NULL, 'R&B', 257, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Al Green', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Here I Am (Come and Take Me)'
)
AND a.name = 'Al Green';

-- [2026-04-01] Boogie Oogie Oogie — A Taste Of Honey
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Boogie Oogie Oogie', 'USA', NULL, 'Disco', 337, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('A Taste Of Honey', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Boogie Oogie Oogie'
)
AND a.name = 'A Taste Of Honey';

-- [2026-04-01] Let It Whip — Dazz Band
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Let It Whip', 'USA', NULL, 'R&B', 281, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Dazz Band', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Let It Whip'
)
AND a.name = 'Dazz Band';

-- [2026-04-01] Atomic Dog — George Clinton
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Atomic Dog', 'USA', NULL, 'Funk', 255, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('George Clinton', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Atomic Dog'
)
AND a.name = 'George Clinton';

-- [2026-04-01] 2 Legit 2 Quit — MC Hammer, Saja
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('2 Legit 2 Quit', 'USA', NULL, 'Hip hop', 336, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('MC Hammer', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '2 Legit 2 Quit'
)
AND a.name = 'MC Hammer';
INSERT INTO artists (name, alias) VALUES ('Saja', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '2 Legit 2 Quit'
)
AND a.name = 'Saja';
UPDATE songs SET title = '2 Legit 2 Quit (feat. Saja)' WHERE title = '2 Legit 2 Quit';

-- [2026-04-01] Leave You Far Behind — Lunatic Calm
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Leave You Far Behind', 'UK', NULL, 'Big Beat', 192, 'English', 'UK');
INSERT INTO artists (name, alias) VALUES ('Lunatic Calm', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Leave You Far Behind'
)
AND a.name = 'Lunatic Calm';

-- [2026-04-01] Them Changes — Thundercat
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Them Changes', 'USA', NULL, 'Funk', 188, 'English', 'Funk');
INSERT INTO artists (name, alias) VALUES ('Thundercat', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Them Changes'
)
AND a.name = 'Thundercat';

-- [2026-04-01] Pulse (Mahjong Instrumental Mix) — Malexa
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Pulse (Mahjong Instrumental Mix)', 'UK', NULL, 'Electronic', 471, NULL, 'contemp');
INSERT INTO artists (name, alias) VALUES ('Malexa', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Pulse (Mahjong Instrumental Mix)'
)
AND a.name = 'Malexa';

-- [2026-04-01] Get Wavey — Redlight
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Get Wavey', 'USA', NULL, 'Electronic', 310, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Redlight', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Get Wavey'
)
AND a.name = 'Redlight';

-- [2026-04-01] texture bath — FM Skyline
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('texture bath', 'USA', NULL, 'Vaporwave', 222, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('FM Skyline', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'texture bath'
)
AND a.name = 'FM Skyline';

-- [2026-04-01] 2 Phút Hơn (KAIZ Remix) — Pháo
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('2 Phút Hơn (KAIZ Remix)', 'Vietnam', '2 Phút Hơn (KAIZ Remix)', 'Electronic', 184, 'Vietnamese', 'Viet');
INSERT INTO artists (name, alias) VALUES ('Pháo', 'Pháo');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '2 Phút Hơn (KAIZ Remix)'
)
AND a.name = 'Pháo';

-- [2026-04-02] Muito Calor — Ozuna, Anitta
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Muito Calor', NULL, NULL, 'Latin', 185, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Ozuna', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Muito Calor'
)
AND a.name = 'Ozuna';
INSERT INTO artists (name, alias) VALUES ('Anitta', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Muito Calor'
)
AND a.name = 'Anitta';

-- [2026-04-02] Mamacita — Jason Derulo, Farruko
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Mamacita', 'USA', NULL, 'Pop', 204, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Jason Derulo', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Mamacita'
)
AND a.name = 'Jason Derulo';
INSERT INTO artists (name, alias) VALUES ('Farruko', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Mamacita'
)
AND a.name = 'Farruko';
UPDATE songs SET title = 'Mamacita (feat. Farruko)' WHERE title = 'Mamacita';

-- [2026-04-02] Soy Yo — Bomba Estéreo
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Soy Yo', 'Colombia', NULL, 'Electrocumbia', 159, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Bomba Estéreo', 'Bomba Estéreo');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Soy Yo'
)
AND a.name = 'Bomba Estéreo';

-- [2026-04-02] Um Côco — Zuco 103
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Um Côco', 'Netherlands', 'Um Côco', 'Brazilectro', 260, NULL, 'Latin');
INSERT INTO artists (name, alias) VALUES ('Zuco 103', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Um Côco'
)
AND a.name = 'Zuco 103';

-- [2026-04-03] 野花香 — 莫斯滿, 老貓
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('野花香', 'China', 'nobana kaori', 'Pop', 192, 'Chinese', 'Cn');
INSERT INTO artists (name, alias) VALUES ('莫斯滿', 'baku shi man');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '野花香'
)
AND a.name = '莫斯滿';
INSERT INTO artists (name, alias) VALUES ('老貓', 'rou');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '野花香'
)
AND a.name = '老貓';

-- [2026-04-03] Doctor — ちゃんみな
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Doctor', 'Japan', NULL, 'Hip hop', 183, 'Japanese', 'J');
INSERT INTO artists (name, alias) VALUES ('ちゃんみな', 'chanmina');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Doctor'
)
AND a.name = 'ちゃんみな';

-- [2026-04-03] FORGIVE ME — ちゃんみな
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('FORGIVE ME', 'Japan', NULL, 'Pop', 143, 'Japanese', 'J');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'FORGIVE ME'
)
AND a.name = 'ちゃんみな';

-- [2026-04-03] help_urself — Ezekiel
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('help_urself', 'UK', NULL, 'Dnb', 140, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Ezekiel', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'help_urself'
)
AND a.name = 'Ezekiel';

-- [2026-04-04] Clear (Jose "Animal" Diaz Remix) — Cybotron
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Clear (Jose "Animal" Diaz Remix)', 'USA', NULL, 'Electro', 294, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Cybotron', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Clear (Jose "Animal" Diaz Remix)'
)
AND a.name = 'Cybotron';

-- [2026-04-04] Addicted — PIXY
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Addicted', 'Korea', NULL, 'Kpop', 197, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('PIXY', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Addicted'
)
AND a.name = 'PIXY';

-- [2026-04-04] SWIPE — ITZY
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('SWIPE', 'Korea', NULL, 'Kpop', 177, 'Korean', 'K');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'SWIPE'
)
AND a.name = 'ITZY';

-- [2026-04-04] Alcohol-Free — TWICE
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Alcohol-Free', 'Korea', NULL, 'Kpop', 210, 'Korean', 'K');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Alcohol-Free'
)
AND a.name = 'TWICE';

-- [2026-04-04] SO BAD — STAYC
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('SO BAD', 'Korea', NULL, 'Kpop', 212, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('STAYC', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'SO BAD'
)
AND a.name = 'STAYC';

-- [2026-04-04] Shh — After School
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Shh', 'Japan', NULL, 'Jpop', 295, 'Japanese', 'K');
INSERT INTO artists (name, alias) VALUES ('After School', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Shh'
)
AND a.name = 'After School';

-- [2026-04-04] Arcarsenal — At the Drive-In
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Arcarsenal', 'USA', NULL, 'Post-hardcore', 174, 'English', 'Rock');
INSERT INTO artists (name, alias) VALUES ('At the Drive-In', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Arcarsenal'
)
AND a.name = 'At the Drive-In';

-- [2026-04-04] Chicken Teriyaki — ROSALÍA
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Chicken Teriyaki', 'Spain', NULL, 'Reggaeton', 122, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('ROSALÍA', 'ROSALÍA');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Chicken Teriyaki'
)
AND a.name = 'ROSALÍA';

-- [2026-04-04] moment — Vierre Cloud
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('moment', 'Australia', NULL, 'Dnb', 129, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Vierre Cloud', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'moment'
)
AND a.name = 'Vierre Cloud';

-- [2026-04-04] Same Song — Digital Underground
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Same Song', 'USA', NULL, 'Hip hop', 390, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Digital Underground', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Same Song'
)
AND a.name = 'Digital Underground';

-- [2026-04-04] B.O.T.A. (Baddest Of Them All) - Edit — Eliza Rose, Interplanetary Criminal
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('B.O.T.A. (Baddest Of Them All) - Edit', 'UK', NULL, 'House', 226, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Eliza Rose', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'B.O.T.A. (Baddest Of Them All) - Edit'
)
AND a.name = 'Eliza Rose';
INSERT INTO artists (name, alias) VALUES ('Interplanetary Criminal', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'B.O.T.A. (Baddest Of Them All) - Edit'
)
AND a.name = 'Interplanetary Criminal';

-- [2026-04-05] Just Be Good to Me — the S.O.S. Band
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Just Be Good to Me', 'USA', NULL, 'Funk', 250, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('the S.O.S. Band', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Just Be Good to Me'
)
AND a.name = 'the S.O.S. Band';

-- [2026-04-05] So Ruff, so Tuff — Zapp
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('So Ruff, so Tuff', 'USA', NULL, 'Funk', 215, 'English', 'Ox');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'So Ruff, so Tuff'
)
AND a.name = 'Zapp';

-- [2026-04-05] Burn Rubber On Me (Why You Wanna Hurt Me) — The Gap Band
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Burn Rubber On Me (Why You Wanna Hurt Me)', 'USA', NULL, 'Funk', 252, 'English', 'Ox/Cx');
INSERT INTO artists (name, alias) VALUES ('The Gap Band', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Burn Rubber On Me (Why You Wanna Hurt Me)'
)
AND a.name = 'The Gap Band';

-- [2026-04-05] Operator — Midnight Star
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Operator', 'USA', NULL, 'R&B dance', 448, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Midnight Star', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Operator'
)
AND a.name = 'Midnight Star';

-- [2026-04-05] Freak-a-Zoid — Midnight Star
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Freak-a-Zoid', 'USA', NULL, 'Electro', 485, 'English', 'Ox');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Freak-a-Zoid'
)
AND a.name = 'Midnight Star';

-- [2026-04-05] Буду с тобой — 5sta Family

-- [2026-04-05] Зачем — АДЛИН, Килджо, 5sta Family
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Зачем', 'Russia', 'Zachem', 'Phonk', 168, 'Russian', 'R/U');
INSERT INTO artists (name, alias) VALUES ('АДЛИН', 'ADLYN');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Зачем'
)
AND a.name = 'АДЛИН';
INSERT INTO artists (name, alias) VALUES ('Килджо', 'Kyldzho');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Зачем'
)
AND a.name = 'Килджо';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Зачем'
)
AND a.name = '5sta Family';

-- [2026-04-05] Zachem — 6YNTHMANE, 5sta Family, BAbyBoi
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Zachem', 'Russia', NULL, 'phonk pop', 112, 'Russian', 'R/U');
INSERT INTO artists (name, alias) VALUES ('6YNTHMANE', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Zachem'
)
AND a.name = '6YNTHMANE';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Zachem'
)
AND a.name = '5sta Family';
INSERT INTO artists (name, alias) VALUES ('BAbyBoi', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Zachem'
)
AND a.name = 'BAbyBoi';

-- [2026-04-05] Ничья — Nichya
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Ничья', 'Russia', 'Nych''ja', 'Pop', 200, 'Russian', 'R/U');
INSERT INTO artists (name, alias) VALUES ('Nichya', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Ничья'
)
AND a.name = 'Nichya';

-- [2026-04-05] Rapid Racer — Lone
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Rapid Racer', 'UK', NULL, 'Dance', 252, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('Lone', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Rapid Racer'
)
AND a.name = 'Lone';

-- [2026-04-05] Про красивую жизнь — Банд’Эрос
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Про красивую жизнь', 'Russia', 'Pro krasyvuju zhyzn''', 'Pop', 221, 'Russian', 'R/U');
INSERT INTO artists (name, alias) VALUES ('Банд’Эрос', 'Band’Эros');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Про красивую жизнь'
)
AND a.name = 'Банд’Эрос';

-- [2026-04-05] Дай пять — Банд’Эрос
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Дай пять', 'Russia', 'Daj pjat''', 'Pop', 181, 'Russian', 'R/U');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Дай пять'
)
AND a.name = 'Банд’Эрос';

-- [2026-04-05] Footsteps in the Dark, Pts. 1 & 2 — The Isley Brothers

-- [2026-04-05] Coffin Nails — MF DOOM
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Coffin Nails', 'USA', NULL, NULL, 176, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('MF DOOM', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Coffin Nails'
)
AND a.name = 'MF DOOM';

-- [2026-04-05] Hot Summer — Monrose
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Hot Summer', 'Germany', NULL, 'Dance pop', 210, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Monrose', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Hot Summer'
)
AND a.name = 'Monrose';

-- [2026-04-05] Never Leave You (Uh Oooh, Uh Oooh) — Lumidee
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Never Leave You (Uh Oooh, Uh Oooh)', 'USA', NULL, 'R&B', 184, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Lumidee', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Never Leave You (Uh Oooh, Uh Oooh)'
)
AND a.name = 'Lumidee';

-- [2026-04-05] Righteous — Mo Beats
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Righteous', 'USA', NULL, 'Hip hop', 163, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('Mo Beats', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Righteous'
)
AND a.name = 'Mo Beats';

-- [2026-04-05] Mais Que Nada — Sergio Mendes & Brasil '66
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Mais Que Nada', 'Brazil', NULL, 'Bossa Nova', 159, 'Portuguese', 'Br');
INSERT INTO artists (name, alias) VALUES ('Sergio Mendes & Brasil ''66', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Mais Que Nada'
)
AND a.name = 'Sergio Mendes & Brasil ''66';

-- [2026-04-05] Kerosene — Crystal Castles
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Kerosene', 'Canada', NULL, 'House', 192, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('Crystal Castles', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Kerosene'
)
AND a.name = 'Crystal Castles';

-- [2026-04-05] Lying Has To Stop — Soft Hair, LA Priest, Connan Mockasin
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Lying Has To Stop', NULL, NULL, 'Funk pop', 356, 'English', 'Contemp');
INSERT INTO artists (name, alias) VALUES ('Soft Hair', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lying Has To Stop'
)
AND a.name = 'Soft Hair';
INSERT INTO artists (name, alias) VALUES ('LA Priest', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lying Has To Stop'
)
AND a.name = 'LA Priest';
INSERT INTO artists (name, alias) VALUES ('Connan Mockasin', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lying Has To Stop'
)
AND a.name = 'Connan Mockasin';
UPDATE songs SET title = 'Lying Has To Stop (feat. LA Priest, Connan Mockasin)' WHERE title = 'Lying Has To Stop';

-- [2026-04-05] Drowning Butterflies — The Cleaners From Venus
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Drowning Butterflies', 'UK', NULL, 'Indie pop', 300, 'English', 'UK');
INSERT INTO artists (name, alias) VALUES ('The Cleaners From Venus', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Drowning Butterflies'
)
AND a.name = 'The Cleaners From Venus';

-- [2026-04-05] See Tình (Cukak Remix) — Hoàng Thùy Linh, Cukak
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('See Tình (Cukak Remix)', 'Vietnam', 'See Tình (Cukak Remix)', 'V-pop', 170, 'Vietnamese', 'Viet');
INSERT INTO artists (name, alias) VALUES ('Hoàng Thùy Linh', 'Hoàng Thùy Linh');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'See Tình (Cukak Remix)'
)
AND a.name = 'Hoàng Thùy Linh';
INSERT INTO artists (name, alias) VALUES ('Cukak', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'See Tình (Cukak Remix)'
)
AND a.name = 'Cukak';
UPDATE songs SET title = 'See Tình (Cukak Remix) (feat. Cukak)' WHERE title = 'See Tình (Cukak Remix)';

-- [2026-04-05] Tension — Kylie Minogue
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Tension', 'Australia', NULL, 'Dance pop', 216, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Kylie Minogue', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Tension'
)
AND a.name = 'Kylie Minogue';

-- [2026-04-05] Paso (The Nini Anthem) - Radio Edit — Sak Noel
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Paso (The Nini Anthem) - Radio Edit', 'Spain', NULL, 'Dance pop', 197, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Sak Noel', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Paso (The Nini Anthem) - Radio Edit'
)
AND a.name = 'Sak Noel';

-- [2026-04-05] Monstrão — DENNIS, Anitta
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Monstrão', 'Brazil', 'Monstrão', 'Tamborzão', 127, 'Portuguese', 'Br');
INSERT INTO artists (name, alias) VALUES ('DENNIS', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Monstrão'
)
AND a.name = 'DENNIS';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Monstrão'
)
AND a.name = 'Anitta';
