-- Radio Catalogue data
-- Auto-generated by rebuild_data_sql.py
PRAGMA foreign_keys = ON;

INSERT INTO artists (name, alias) VALUES ('Charli XCX', NULL);
INSERT INTO artists (name, alias) VALUES ('No Doubt', NULL);
INSERT INTO artists (name, alias) VALUES ('Buju Banton', NULL);
INSERT INTO artists (name, alias) VALUES ('Neon Indian', NULL);
INSERT INTO artists (name, alias) VALUES ('Classixxx', NULL);
INSERT INTO artists (name, alias) VALUES ('Nancy Whang', NULL);
INSERT INTO artists (name, alias) VALUES ('Björk', 'Bjork');
INSERT INTO artists (name, alias) VALUES ('Eric B. & Rakim', NULL);
INSERT INTO artists (name, alias) VALUES ('4minute', NULL);
INSERT INTO artists (name, alias) VALUES ('Perturbator', NULL);
INSERT INTO artists (name, alias) VALUES ('Cheryl Lynn', NULL);
INSERT INTO artists (name, alias) VALUES ('Britney Spears', NULL);
INSERT INTO artists (name, alias) VALUES ('The Brothers Johnson', NULL);
INSERT INTO artists (name, alias) VALUES ('ADULT.', NULL);
INSERT INTO artists (name, alias) VALUES ('Trang Pháp', 'Trang Phap');
INSERT INTO artists (name, alias) VALUES ('Nadine Coyle', NULL);
INSERT INTO artists (name, alias) VALUES ('5sta Family', NULL);
INSERT INTO artists (name, alias) VALUES ('Adrian Lux', NULL);
INSERT INTO artists (name, alias) VALUES ('Rebecca & Fiona', NULL);
INSERT INTO artists (name, alias) VALUES ('Luna', NULL);
INSERT INTO artists (name, alias) VALUES ('Miss Kittin', NULL);
INSERT INTO artists (name, alias) VALUES ('Xeno & Oaklander', NULL);
INSERT INTO artists (name, alias) VALUES ('2ne1', NULL);
INSERT INTO artists (name, alias) VALUES ('Afterschool', NULL);
INSERT INTO artists (name, alias) VALUES ('Yazoo', NULL);
INSERT INTO artists (name, alias) VALUES ('Girls Aloud', NULL);
INSERT INTO artists (name, alias) VALUES ('Covenant', NULL);
INSERT INTO artists (name, alias) VALUES ('Monatik', NULL);
INSERT INTO artists (name, alias) VALUES ('Dorofeeva', NULL);
INSERT INTO artists (name, alias) VALUES ('OTOY', NULL);
INSERT INTO artists (name, alias) VALUES ('Kard', NULL);
INSERT INTO artists (name, alias) VALUES ('Bronski Beat', NULL);
INSERT INTO artists (name, alias) VALUES ('Sneaker Pimps', NULL);
INSERT INTO artists (name, alias) VALUES ('Um Jung Hwa', NULL);
INSERT INTO artists (name, alias) VALUES ('HyunA', NULL);
INSERT INTO artists (name, alias) VALUES ('CHANGMO', NULL);
INSERT INTO artists (name, alias) VALUES ('Zapp', NULL);
INSERT INTO artists (name, alias) VALUES ('MC Breed', NULL);
INSERT INTO artists (name, alias) VALUES ('DFC', NULL);
INSERT INTO artists (name, alias) VALUES ('Chicago', NULL);
INSERT INTO artists (name, alias) VALUES ('Never Dull', NULL);
INSERT INTO artists (name, alias) VALUES ('Crystal Waters', NULL);
INSERT INTO artists (name, alias) VALUES ('The Isley Brothers', NULL);
INSERT INTO artists (name, alias) VALUES ('Ice Cube', NULL);
INSERT INTO artists (name, alias) VALUES ('Chaka Khan', NULL);
INSERT INTO artists (name, alias) VALUES ('Stardust', NULL);
INSERT INTO artists (name, alias) VALUES ('Hikaru Utada', 'Utada Hikaru');
INSERT INTO artists (name, alias) VALUES ('宇多田ヒカル', 'Hikaru Utada');
INSERT INTO artists (name, alias) VALUES ('Goose', NULL);
INSERT INTO artists (name, alias) VALUES ('Mary Jane Girls', NULL);
INSERT INTO artists (name, alias) VALUES ('Neneh Cherry', NULL);
INSERT INTO artists (name, alias) VALUES ('Curtis Mayfield', NULL);
INSERT INTO artists (name, alias) VALUES ('Hashim', NULL);
INSERT INTO artists (name, alias) VALUES ('Run-D.M.C.', NULL);
INSERT INTO artists (name, alias) VALUES ('Black Uhuru', NULL);
INSERT INTO artists (name, alias) VALUES ('Burning Spear', NULL);
INSERT INTO artists (name, alias) VALUES ('Yellowman', NULL);
INSERT INTO artists (name, alias) VALUES ('Ohio Players', NULL);
INSERT INTO artists (name, alias) VALUES ('the GazettE', NULL);
INSERT INTO artists (name, alias) VALUES ('Parliament', NULL);
INSERT INTO artists (name, alias) VALUES ('Aphex Twin', NULL);
INSERT INTO artists (name, alias) VALUES ('Sister Sledge', NULL);
INSERT INTO artists (name, alias) VALUES ('Foxy', NULL);
INSERT INTO artists (name, alias) VALUES ('TWICE', NULL);
INSERT INTO artists (name, alias) VALUES ('ITZY', NULL);
INSERT INTO artists (name, alias) VALUES ('MAMAMOO', NULL);
INSERT INTO artists (name, alias) VALUES ('CHIC', NULL);
INSERT INTO artists (name, alias) VALUES ('U-Roy', NULL);
INSERT INTO artists (name, alias) VALUES ('Amazulu', NULL);
INSERT INTO artists (name, alias) VALUES ('Die & Interface', NULL);
INSERT INTO artists (name, alias) VALUES ('William Cartwright', NULL);
INSERT INTO artists (name, alias) VALUES ('ElementFour', NULL);
INSERT INTO artists (name, alias) VALUES ('MIYAVI', NULL);
INSERT INTO artists (name, alias) VALUES ('D''espairsRay', NULL);
INSERT INTO artists (name, alias) VALUES ('Ms Nina', NULL);
INSERT INTO artists (name, alias) VALUES ('Beauty Brain', NULL);
INSERT INTO artists (name, alias) VALUES ('비디오로즈', 'bidi-olojeu');
INSERT INTO artists (name, alias) VALUES ('FAKY', NULL);
INSERT INTO artists (name, alias) VALUES ('ЯАVЬ', 'JaAV''');
INSERT INTO artists (name, alias) VALUES ('IOSYS', NULL);
INSERT INTO artists (name, alias) VALUES ('박미경', 'bagmigyeong');
INSERT INTO artists (name, alias) VALUES ('Brown Eyed Girls', NULL);
INSERT INTO artists (name, alias) VALUES ('Lindsay Lohan', NULL);
INSERT INTO artists (name, alias) VALUES ('Hillary Duff', NULL);
INSERT INTO artists (name, alias) VALUES ('KC & The Sunshine Band', NULL);
INSERT INTO artists (name, alias) VALUES ('김건모', 'gimgeonmo');
INSERT INTO artists (name, alias) VALUES ('에쵸티', 'echyoti');
INSERT INTO artists (name, alias) VALUES ('Al Green', NULL);
INSERT INTO artists (name, alias) VALUES ('A Taste Of Honey', NULL);
INSERT INTO artists (name, alias) VALUES ('Dazz Band', NULL);
INSERT INTO artists (name, alias) VALUES ('George Clinton', NULL);
INSERT INTO artists (name, alias) VALUES ('MC Hammer', NULL);
INSERT INTO artists (name, alias) VALUES ('Saja', NULL);
INSERT INTO artists (name, alias) VALUES ('Lunatic Calm', NULL);
INSERT INTO artists (name, alias) VALUES ('Thundercat', NULL);
INSERT INTO artists (name, alias) VALUES ('Malexa', NULL);
INSERT INTO artists (name, alias) VALUES ('Redlight', NULL);
INSERT INTO artists (name, alias) VALUES ('FM Skyline', NULL);
INSERT INTO artists (name, alias) VALUES ('Pháo', 'Pháo');
INSERT INTO artists (name, alias) VALUES ('Ozuna', NULL);
INSERT INTO artists (name, alias) VALUES ('Anitta', NULL);
INSERT INTO artists (name, alias) VALUES ('Jason Derulo', NULL);
INSERT INTO artists (name, alias) VALUES ('Farruko', NULL);
INSERT INTO artists (name, alias) VALUES ('Bomba Estéreo', 'Bomba Estéreo');
INSERT INTO artists (name, alias) VALUES ('Zuco 103', NULL);
INSERT INTO artists (name, alias) VALUES ('莫斯滿', 'baku shi man');
INSERT INTO artists (name, alias) VALUES ('老貓', 'rou ');
INSERT INTO artists (name, alias) VALUES ('ちゃんみな', 'chanmina');
INSERT INTO artists (name, alias) VALUES ('Ezekiel', NULL);
INSERT INTO artists (name, alias) VALUES ('Cybotron', NULL);
INSERT INTO artists (name, alias) VALUES ('PIXY', NULL);
INSERT INTO artists (name, alias) VALUES ('STAYC', NULL);
INSERT INTO artists (name, alias) VALUES ('After School', NULL);
INSERT INTO artists (name, alias) VALUES ('At the Drive-In', NULL);
INSERT INTO artists (name, alias) VALUES ('ROSALÍA', 'ROSALÍA');
INSERT INTO artists (name, alias) VALUES ('Vierre Cloud', NULL);
INSERT INTO artists (name, alias) VALUES ('Digital Underground', NULL);
INSERT INTO artists (name, alias) VALUES ('Eliza Rose', NULL);
INSERT INTO artists (name, alias) VALUES ('Interplanetary Criminal', NULL);
INSERT INTO artists (name, alias) VALUES ('the S.O.S. Band', NULL);
INSERT INTO artists (name, alias) VALUES ('The Gap Band', NULL);
INSERT INTO artists (name, alias) VALUES ('Midnight Star', NULL);
INSERT INTO artists (name, alias) VALUES ('АДЛИН', 'ADLYN');
INSERT INTO artists (name, alias) VALUES ('Килджо', 'Kyldzho');
INSERT INTO artists (name, alias) VALUES ('6YNTHMANE', NULL);
INSERT INTO artists (name, alias) VALUES ('BAbyBoi', NULL);
INSERT INTO artists (name, alias) VALUES ('Nichya', NULL);
INSERT INTO artists (name, alias) VALUES ('Lone', NULL);
INSERT INTO artists (name, alias) VALUES ('Банд’Эрос', 'Band’Eros');
INSERT INTO artists (name, alias) VALUES ('MF DOOM', NULL);
INSERT INTO artists (name, alias) VALUES ('Monrose', NULL);
INSERT INTO artists (name, alias) VALUES ('Lumidee', NULL);
INSERT INTO artists (name, alias) VALUES ('Mo Beats', NULL);
INSERT INTO artists (name, alias) VALUES ('Sergio Mendes & Brasil ''66', NULL);
INSERT INTO artists (name, alias) VALUES ('Crystal Castles', NULL);
INSERT INTO artists (name, alias) VALUES ('Soft Hair', NULL);
INSERT INTO artists (name, alias) VALUES ('LA Priest', NULL);
INSERT INTO artists (name, alias) VALUES ('Connan Mockasin', NULL);
INSERT INTO artists (name, alias) VALUES ('The Cleaners From Venus', NULL);
INSERT INTO artists (name, alias) VALUES ('Hoàng Thùy Linh', 'Hoàng Thùy Linh');
INSERT INTO artists (name, alias) VALUES ('Cukak', NULL);
INSERT INTO artists (name, alias) VALUES ('Kylie Minogue', NULL);
INSERT INTO artists (name, alias) VALUES ('Sak Noel', NULL);
INSERT INTO artists (name, alias) VALUES ('DENNIS', NULL);
INSERT INTO artists (name, alias) VALUES ('Gregory Isaacs', NULL);
INSERT INTO artists (name, alias) VALUES ('The Damned', NULL);
INSERT INTO artists (name, alias) VALUES ('Iglooghost', NULL);
INSERT INTO artists (name, alias) VALUES ('Raffaella Carrà', 'Raffaella Carrà');
INSERT INTO artists (name, alias) VALUES ('Jaxomy', NULL);
INSERT INTO artists (name, alias) VALUES ('Agatino Romero', NULL);
INSERT INTO artists (name, alias) VALUES ('Coco Jones', NULL);
INSERT INTO artists (name, alias) VALUES ('YOUNG POSSE', NULL);
INSERT INTO artists (name, alias) VALUES ('Alphaville', NULL);
INSERT INTO artists (name, alias) VALUES ('Shygirl', NULL);
INSERT INTO artists (name, alias) VALUES ('SG Lewis', NULL);
INSERT INTO artists (name, alias) VALUES ('Cosha', NULL);
INSERT INTO artists (name, alias) VALUES ('Raffertie', NULL);
INSERT INTO artists (name, alias) VALUES ('budAGE', NULL);
INSERT INTO artists (name, alias) VALUES ('Imogen Heap', NULL);
INSERT INTO artists (name, alias) VALUES ('The Hardkiss', NULL);
INSERT INTO artists (name, alias) VALUES ('KAZAKY', NULL);
INSERT INTO artists (name, alias) VALUES ('DOROFEEVA', NULL);
INSERT INTO artists (name, alias) VALUES ('Wellboy', NULL);
INSERT INTO artists (name, alias) VALUES ('Parfeniuk', NULL);
INSERT INTO artists (name, alias) VALUES ('KOLA', NULL);
INSERT INTO artists (name, alias) VALUES ('Sasha Lopez', NULL);
INSERT INTO artists (name, alias) VALUES ('Misha Miller', NULL);
INSERT INTO artists (name, alias) VALUES ('SICKOTOY', NULL);
INSERT INTO artists (name, alias) VALUES ('SadSvit', NULL);

INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Nuclear Seasons', 'UK', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('New', 'USA', 'Alternative Rock', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Murderer', 'Jamaica', 'Reggae', 'English', 'Pol', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Change of Coast', 'USA', 'Soundtrack', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('All You''re Waiting For (feat. Nancy Whang)', 'USA', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Bachelorette', 'Iceland', 'Orchestral Pop', 'English', 'Sy', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Hunter', 'Iceland', 'Symphonic Pop', 'English', 'Sy', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Move the Crowd', 'USA', 'Hip-hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Eric B. is President', 'USA', 'Hip-hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('What''s Your Name?', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Future Club', 'USA', 'Electronic', 'none', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Got to Be Real', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Scary', 'Japan', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Strawberry Letter 23', 'USA', 'Psychedelic soul', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Hand to Phone (Cordless Mix)', 'USA', 'Electronic', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Lựa Chọn', 'Vietnam', 'Viet pop', 'Vietnamese', 'Viet', 'Lựa Chọn');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Chained', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Insatiable', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Put Your Hands Up', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Runnin''', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Буду с тобой', 'Russia', 'Pop', 'Russian', 'R/U', 'Budu s toboy');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Boy (Hardwell Remix) (feat. Rebecca & Fiona)', 'USA', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Free Somebody', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Keep on Doin''', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Bassline', 'France', 'Electropop', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rendez-Vous d''Or', 'USA', 'Dark wave', 'French', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Werke', 'USA', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Insomnia', 'USA', 'Dark wave', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('난 바빠', 'Korea', 'Kpop', 'Korean', 'K', 'Nan bappa');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Eyeline', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Situation', 'UK', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('It''s Magic', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Girl Overboard', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('What You Crying For', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Memory of You', 'UK', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('How''s This?', 'Korea', 'Korean Trap', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Stalker', 'Sweden', 'Industrial', 'English', 'Industrial', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Vitamin D', 'Ukraine', 'Pop', 'Russian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Выходной', 'Ukraine', 'Pop', 'Russian', 'R/U', 'Vykhodnoy');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Глубоко...', 'Ukraine', 'Pop', 'Russian', 'R/U', 'Gluboko...');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('If you know what I mean', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('I.D.', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rumor', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Smalltown Boy', 'UK', 'Synthpop', 'English', '80s', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Tesko Suicide', 'UK', 'Alt dance', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Invitation', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('RSVP (feat. CHANGMO)', 'Korea', 'Kpop', 'Korean', 'Pair', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('More Bounce to the Ounce', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Ain''t No Future in Yo'' Frontin''', 'USA', 'G-funk', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Street Player', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('In My Mind (feat. Crystal Waters)', 'USA', 'House', 'Engish', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Footsteps in the Dark, Pts. 1 & 2', 'USA', 'R&B', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('It Was a Good Day', 'USA', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Fate', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Music Sounds Better with You', 'France', 'House', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Colors', 'Japan', 'Synthpop', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('テイク５', 'Japan', 'Dance pop', 'Japanese', 'J', 'Take 5');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('嘘みたいな (I Love You)', 'Japan', 'Pop', 'Japanese', 'J', 'uso mitaina  (I Love You )');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Synrise', 'UK', 'Electronic', 'n/a', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('All Night Long', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Buffalo Stance', 'UK', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Move On Up (Single Edit)', 'USA', 'Progressive soul', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('We''re Rocking The Planet', 'USA', 'Electro', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Al-Naafiysh (The Soul)', 'USA', 'Electro', NULL, 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Sucker M.C.''s (Krush-Groove 1)', 'USA', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Sponji Reggae', 'Jamaica', 'Roots reggae', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Columbus - 2002 Remastered Version', 'Jamaica', 'Roots reggae', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Zungguzungguguzungguzeng', 'Jamaica', 'Dancehall', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Nobody Move Nobody Get Hurt', 'Jamaica', 'Dancehall', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Funky Worm', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Skin Tight', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('FILTH IN THE BEAUTY', 'Japan', 'Visual Kei', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Give Up The Funk (Tear The Roof Off The Sucker)', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Heliosphan', 'UK', 'Ambient', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('He''s the Greatest Dancer', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Get Off', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Likey', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('CHERRY', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('HIP', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('I Can Make You Dance', 'USA', 'Disco', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Good Times', 'USA', 'Disco', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Natty Rebel', 'USA', 'Dub', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Moonlight Romance', 'UK', 'Soul', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Bright Lights (Netsky Remix) (feat. William Cartwright)', 'UK', 'Electronic', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Big Brother UK TV Theme (Vocal Mix - Radio Edit)', 'UK', 'Trance', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('セニョール セニョーラ セニョリータ', 'Japan', 'Pop', 'Japanese', 'J', 'senyooru   senyoora   senyoriita');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('MIЯROR', 'Japan', 'Visual kei', 'Japanese', 'J', 'MIJaROR');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Lost Scene', 'Japan', 'Visual kei', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Tu Sicaria', 'Spain', 'Perreo', 'Spanish', 'Latin', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('홀리가든', 'Korea', 'Synth pop', 'English', 'K', 'holligadeun');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Afterglow', 'Japan', 'Jpop', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('В ТЕМНОТЕ ТАНЦУЙ', 'Russia', 'Pop', 'Russian', 'R/U', 'V TEMNOTE TANTsUJ');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Taboo Tears You Up', 'Japan', 'Touhou', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('이브의 경고', 'Korea', 'Dance ballad', 'Korean', 'K', 'ibeu-ui gyeonggo');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Abracadabra', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rumors', 'USA', 'Pop', 'English', 'cringe', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('With Love', 'USA', 'Pop', 'English', 'cringe', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Boogie Shoes', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('잘못된 만남', 'Korea', 'Kpop', 'Korean', 'K/Ox', 'jalmosdoen mannam');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Outside Castle (The Castle Outsiders)', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Here I Am (Come and Take Me)', 'USA', 'R&B', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Boogie Oogie Oogie', 'USA', 'Disco', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Let It Whip', 'USA', 'R&B', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Atomic Dog', 'USA', 'Funk', 'English', 'Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('2 Legit 2 Quit (feat. Saja)', 'USA', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Leave You Far Behind', 'UK', 'Big Beat', 'English', 'UK', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Them Changes', 'USA', 'Funk', 'English', 'Funk', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Pulse (Mahjong Instrumental Mix)', 'UK', 'Electronic', NULL, 'contemp', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Get Wavey', 'USA', 'Electronic', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('texture bath', 'USA', 'Vaporwave', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('2 Phút Hơn (KAIZ Remix)', 'Vietnam', 'Electronic', 'Vietnamese', 'Viet', '2 Phút Hơn (KAIZ Remix)');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Muito Calor', NULL, 'Latin', 'Spanish', 'Latin', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Mamacita (feat. Farruko)', 'USA', 'Pop', 'Spanish', 'Latin', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Soy Yo', 'Colombia', 'Electrocumbia', 'Spanish', 'Latin', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Um Côco', 'Netherlands', 'Brazilectro', NULL, 'Latin', 'Um Côco');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('野花香', 'China', 'Pop', 'Chinese', 'Cn', 'nobana kaori');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Doctor', 'Japan', 'Hip hop', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('FORGIVE ME', 'Japan', 'Pop', 'Japanese', 'J', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('help_urself', 'UK', 'Dnb', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Clear (Jose "Animal" Diaz Remix)', 'USA', 'Electro', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Addicted', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('SWIPE', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Alcohol-Free', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('SO BAD', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Shh', 'Japan', 'Jpop', 'Japanese', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Arcarsenal', 'USA', 'Post-hardcore', 'English', 'Rock', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Chicken Teriyaki', 'Spain', 'Reggaeton', 'Spanish', 'Latin', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('moment', 'Australia', 'Dnb', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Same Song', 'USA', 'Hip hop', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('B.O.T.A. (Baddest Of Them All) - Edit', 'UK', 'House', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Just Be Good to Me', 'USA', 'Funk', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('So Ruff, so Tuff', 'USA', 'Funk', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Burn Rubber On Me (Why You Wanna Hurt Me)', 'USA', 'Funk', 'English', 'Ox/Cx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Operator', 'USA', 'R&B dance', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Freak-a-Zoid', 'USA', 'Electro', 'English', 'Ox', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Зачем', 'Russia', 'Phonk', 'Russian', 'R/U', 'Zachem');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Zachem', 'Russia', 'phonk pop', 'Russian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Ничья', 'Russia', 'Pop', 'Russian', 'R/U', 'Nych''ja');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Rapid Racer', 'UK', 'Dance', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Про красивую жизнь', 'Russia', 'Pop', 'Russian', 'R/U', 'Pro krasyvuju zhyzn''');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Дай пять', 'Russia', 'Pop', 'Russian', 'R/U', 'Daj pjat''');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Coffin Nails', 'USA', NULL, NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Hot Summer', 'Germany', 'Dance pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Never Leave You (Uh Oooh, Uh Oooh)', 'USA', 'R&B', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Righteous', 'USA', 'Hip hop', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Mais Que Nada', 'Brazil', 'Bossa Nova', 'Portuguese', 'Br', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Kerosene', 'Canada', 'House', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Lying Has To Stop (feat. LA Priest, Connan Mockasin)', NULL, 'Funk pop', 'English', 'Contemp', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Drowning Butterflies', 'UK', 'Indie pop', 'English', 'UK', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('See Tình (Cukak Remix) (feat. Cukak)', 'Vietnam', 'V-pop', 'Vietnamese', 'Viet', 'See Tình (Cukak Remix)');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Tension', 'Australia', 'Dance pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Paso (The Nini Anthem) - Radio Edit', 'Spain', 'Dance pop', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Monstrão', 'Brazil', 'Tamborzão', 'Portuguese', 'Br', 'Monstrão');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Night Nurse', 'Jamaica', 'Reggae', 'English', 'Reggae', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Nasty', 'UK', 'Punk', 'English', 'UK', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Coral Mimic', 'UK', 'Industrial', 'English', 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Pedro', NULL, 'EDM', 'Italian', 'It', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Here We Go (Uh Oh)', 'USA', 'R&B', 'English', 'R&B', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Ate That', 'Korea', 'Kpop', 'Korean', 'K', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Sounds Like a Melody', 'UK', 'Synth pop', 'English', 'UK', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('mr useless (feat. SG Lewis)', 'UK', 'Dance pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('thicc (feat. Cosha)', 'UK', 'Dance pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('The Substance', 'UK', 'Dark ambient', NULL, 'Fx', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Vmeste My', 'Russia', 'Dark pop', 'Russian', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Headlock', 'UK', 'Electropop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Strange Moves (feat. KAZAKY)', 'Ukraine', 'Electropop', 'English', 'R/U', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Кохаю, але не зовсім', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', 'Kokhaju, ale ne zovsim');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Японія', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', 'Japonija');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Забий', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', 'Zabyj');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Температура', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', 'Temperatura');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Долоні', 'Ukraine', 'Dance pop', 'Ukrainian', 'R/U', 'Doloni');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Smoke Me', 'Moldova', 'Pop', 'English', 'Pop', NULL);
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Touché', 'Moldova', 'Pop', 'French', 'Pop', 'Touché');
INSERT INTO songs (title, genre, language, notes, alias) VALUES ('Касета', 'Ukraine', 'Post punk', 'Ukrainian', 'R/U', 'Kaseta');

INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (1, 1, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (2, 2, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (3, 3, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (4, 4, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (5, 5, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (5, 6, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (6, 7, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (7, 7, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (8, 8, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (9, 8, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (10, 9, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (11, 10, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (12, 11, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (13, 12, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (14, 13, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (15, 14, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (16, 15, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (17, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (18, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (19, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (20, 16, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (21, 17, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (22, 18, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (22, 19, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (23, 20, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (24, 20, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (25, 21, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (26, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (27, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (28, 22, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (29, 23, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (30, 24, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (31, 25, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (32, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (33, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (34, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (35, 26, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (36, 36, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (37, 28, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (38, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (39, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (40, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (40, 30, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (41, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (41, 30, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (42, 29, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (42, 31, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (43, 32, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (44, 33, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (45, 34, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (46, 35, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (47, 36, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (47, 37, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (48, 38, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (49, 39, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (49, 40, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (50, 41, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (51, 42, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (51, 43, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (52, 44, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (53, 45, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (54, 46, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (55, 47, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (56, 48, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (57, 49, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (58, 49, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (59, 50, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (60, 51, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (61, 52, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (62, 53, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (63, 54, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (64, 54, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (65, 55, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (66, 56, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (67, 57, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (68, 58, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (69, 58, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (70, 59, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (71, 59, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (72, 60, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (73, 61, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (74, 62, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (75, 63, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (76, 64, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (77, 65, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (78, 66, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (79, 67, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (80, 38, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (81, 68, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (82, 69, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (83, 70, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (84, 71, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (84, 72, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (85, 73, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (86, 74, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (87, 75, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (88, 75, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (89, 76, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (89, 77, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (90, 78, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (91, 79, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (92, 80, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (93, 81, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (94, 82, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (95, 83, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (96, 84, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (97, 85, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (98, 86, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (99, 87, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (100, 88, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (101, 89, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (102, 90, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (103, 91, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (104, 92, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (105, 93, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (105, 94, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (106, 95, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (107, 96, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (108, 97, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (109, 98, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (110, 99, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (111, 100, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (112, 101, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (112, 102, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (113, 103, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (113, 104, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (114, 105, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (115, 106, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (116, 107, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (116, 108, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (117, 109, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (118, 109, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (119, 110, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (120, 111, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (121, 112, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (122, 66, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (123, 65, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (124, 113, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (125, 114, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (126, 115, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (127, 116, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (128, 117, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (129, 118, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (130, 119, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (130, 120, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (131, 121, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (132, 38, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (133, 122, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (134, 123, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (135, 123, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (136, 17, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (136, 124, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (136, 125, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (137, 17, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (137, 126, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (137, 127, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (138, 128, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (139, 129, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (140, 130, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (141, 130, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (142, 131, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (143, 132, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (144, 133, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (145, 134, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (146, 135, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (147, 136, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (148, 137, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (148, 138, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (148, 139, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (149, 140, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (150, 141, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (150, 142, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (151, 143, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (152, 144, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (153, 102, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (153, 145, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (154, 146, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (155, 147, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (156, 148, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (157, 149, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (157, 150, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (157, 151, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (158, 152, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (159, 153, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (160, 154, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (161, 155, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (161, 156, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (162, 155, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (162, 157, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (163, 158, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (164, 17, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (164, 126, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (164, 159, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (165, 160, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (166, 161, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (166, 162, 'featured');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (167, 163, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (168, 163, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (169, 164, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (169, 165, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (170, 165, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (170, 166, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (171, 165, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (172, 167, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (172, 168, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (173, 168, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (173, 169, 'primary');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) VALUES (174, 170, 'primary');

-- [2026-04-05] Opr — Gesaffelstein
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Opr', 'France', NULL, 'Dark techno', 233, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('Gesaffelstein', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Opr'
)
AND a.name = 'Gesaffelstein';

-- [2026-04-05] I Felt Love — Blue Hawaii
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I Felt Love', 'Canada', NULL, 'Synth pop', 192, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Blue Hawaii', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I Felt Love'
)
AND a.name = 'Blue Hawaii';

-- [2026-04-05] Como La Flor — Selena
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Como La Flor', 'USA', NULL, 'Tejano cumbia', 184, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Selena', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Como La Flor'
)
AND a.name = 'Selena';

-- [2026-04-05] Cry for You — September
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Cry for You', 'Sweden', NULL, 'Dance pop', 209, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('September', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Cry for You'
)
AND a.name = 'September';

-- [2026-04-05] Anthonio — Annie
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Anthonio', 'Norway', NULL, 'Synth pop', 201, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Annie', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Anthonio'
)
AND a.name = 'Annie';

-- [2026-04-05] Lo Siento — SUPER JUNIOR, KARD
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Lo Siento', 'Korea', NULL, 'Latin pop', 226, 'Korean', 'K, Latin');
INSERT INTO artists (name, alias) VALUES ('SUPER JUNIOR', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lo Siento'
)
AND a.name = 'SUPER JUNIOR';
INSERT INTO artists (name, alias) VALUES ('KARD', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Lo Siento'
)
AND a.name = 'KARD';
UPDATE songs SET title = 'Lo Siento (feat. KARD)' WHERE title = 'Lo Siento';

-- [2026-04-05] MASCARA — Nicki Nicole, Duki
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('MASCARA', 'Argentina', NULL, 'Latin', 145, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Nicki Nicole', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'MASCARA'
)
AND a.name = 'Nicki Nicole';
INSERT INTO artists (name, alias) VALUES ('Duki', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'MASCARA'
)
AND a.name = 'Duki';

-- [2026-04-05] Wall Of Sleep (Harvey McKay Remix) — Daniel Avery, HAAi
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Wall Of Sleep (Harvey McKay Remix)', 'UK', NULL, 'Electronic', 293, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Daniel Avery', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Wall Of Sleep (Harvey McKay Remix)'
)
AND a.name = 'Daniel Avery';
INSERT INTO artists (name, alias) VALUES ('HAAi', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Wall Of Sleep (Harvey McKay Remix)'
)
AND a.name = 'HAAi';
UPDATE songs SET title = 'Wall Of Sleep (Harvey McKay Remix) (feat. HAAi)' WHERE title = 'Wall Of Sleep (Harvey McKay Remix)';

-- [2026-04-05] Bésame — Juan Gabriel
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Bésame', 'Mexico', 'Bésame', 'Pop', 248, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Juan Gabriel', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Bésame'
)
AND a.name = 'Juan Gabriel';

-- [2026-04-05] Quimbara — Celia Cruz, Johnny Pacheco
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Quimbara', 'Cuba', NULL, 'Salsa', 291, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Celia Cruz', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Quimbara'
)
AND a.name = 'Celia Cruz';
INSERT INTO artists (name, alias) VALUES ('Johnny Pacheco', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Quimbara'
)
AND a.name = 'Johnny Pacheco';

-- [2026-04-05] Toro Mata — Celia Cruz, Johnny Pacheco
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Toro Mata', 'Cuba', NULL, 'Salsa', 342, 'Spanish', 'Latin');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Toro Mata'
)
AND a.name = 'Celia Cruz';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Toro Mata'
)
AND a.name = 'Johnny Pacheco';

-- [2026-04-05] A Papá — Celia Cruz, Willie Colón
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('A Papá', 'Cuba', 'A Papá', 'Salsa', 250, 'Spanish', 'Latin');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'A Papá'
)
AND a.name = 'Celia Cruz';
INSERT INTO artists (name, alias) VALUES ('Willie Colón', 'Willie Colón');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'A Papá'
)
AND a.name = 'Willie Colón';

-- [2026-04-05] Pun Pun Catalú — Celia Cruz, Willie Colón
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Pun Pun Catalú', 'Cuba', 'Pun Pun Catalú', 'Salsa', 205, 'Spanish', 'Latin');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Pun Pun Catalú'
)
AND a.name = 'Celia Cruz';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Pun Pun Catalú'
)
AND a.name = 'Willie Colón';

-- [2026-04-05] Dulce Habanera — Celia Cruz, Willie Colón
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Dulce Habanera', 'Cuba', NULL, 'Salsa', 246, 'Spanish', 'Latin');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Dulce Habanera'
)
AND a.name = 'Celia Cruz';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Dulce Habanera'
)
AND a.name = 'Willie Colón';

-- [2026-04-05] Movie Disco — Felix Da Housecat
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Movie Disco', 'USA', NULL, 'House funk', 203, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Felix Da Housecat', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Movie Disco'
)
AND a.name = 'Felix Da Housecat';

-- [2026-04-05] EXTRA — 전소미
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('EXTRA', 'Korea', NULL, 'City pop', 150, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('전소미', 'jeonsomi');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'EXTRA'
)
AND a.name = '전소미';

-- [2026-04-05] Sync — TaQ
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Sync', 'Japan', NULL, 'Trance', 230, NULL, 'J');
INSERT INTO artists (name, alias) VALUES ('TaQ', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sync'
)
AND a.name = 'TaQ';

-- [2026-04-05] I'm Ready — Kano
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I''m Ready', 'Italy', NULL, 'Italo disco', 432, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Kano', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I''m Ready'
)
AND a.name = 'Kano';

-- [2026-04-05] Forget Me Nots — Patrice Rushen
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Forget Me Nots', 'USA', NULL, 'Dance funk', 283, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Patrice Rushen', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Forget Me Nots'
)
AND a.name = 'Patrice Rushen';

-- [2026-04-05] Ain't Nobody — Rufus, Chaka Khan
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Ain''t Nobody', 'USA', NULL, 'Funk', 281, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Rufus', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Ain''t Nobody'
)
AND a.name = 'Rufus';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Ain''t Nobody'
)
AND a.name = 'Chaka Khan';

-- [2026-04-05] Never Too Much — Luther Vandross
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Never Too Much', 'USA', NULL, 'R&B', 230, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Luther Vandross', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Never Too Much'
)
AND a.name = 'Luther Vandross';

-- [2026-04-05] Ring My Bell — Anita Ward
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Ring My Bell', 'USA', NULL, 'Disco', 491, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Anita Ward', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Ring My Bell'
)
AND a.name = 'Anita Ward';

-- [2026-04-05] Bootleg — Death Grips
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Bootleg', 'USA', NULL, 'Experimental', 126, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Death Grips', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Bootleg'
)
AND a.name = 'Death Grips';

-- [2026-04-05] This Is Violence Now (Don't Get Me Wrong) — Death Grips
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('This Is Violence Now (Don''t Get Me Wrong)', 'USA', NULL, 'Experimental', 157, 'English', 'Fx');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'This Is Violence Now (Don''t Get Me Wrong)'
)
AND a.name = 'Death Grips';

-- [2026-04-05] Residue — A.G. Cook
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Residue', 'UK', NULL, 'Acid techno', 208, NULL, 'Fx');
INSERT INTO artists (name, alias) VALUES ('A.G. Cook', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Residue'
)
AND a.name = 'A.G. Cook';

-- [2026-04-05] Si un jour — La Femme
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Si un jour', 'France', NULL, 'Synth pop', 158, 'French', 'Fr');
INSERT INTO artists (name, alias) VALUES ('La Femme', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Si un jour'
)
AND a.name = 'La Femme';

-- [2026-04-05] Antes Muerta Que Sencilla — Los Horóscopos De Durango
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Antes Muerta Que Sencilla', 'USA', NULL, 'Duranguense', 170, 'Spanish', 'Latin');
INSERT INTO artists (name, alias) VALUES ('Los Horóscopos De Durango', 'Los Horóscopos De Durango');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Antes Muerta Que Sencilla'
)
AND a.name = 'Los Horóscopos De Durango';

-- [2026-04-05] I can't Wait — Nu Shooz
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I can''t Wait', 'USA', NULL, 'Dance pop', 326, 'English', '80s');
INSERT INTO artists (name, alias) VALUES ('Nu Shooz', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I can''t Wait'
)
AND a.name = 'Nu Shooz';

-- [2026-04-05] Mother's Talk — Tears For Fears
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Mother''s Talk', 'UK', NULL, 'New wave', 306, 'English', '80s');
INSERT INTO artists (name, alias) VALUES ('Tears For Fears', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Mother''s Talk'
)
AND a.name = 'Tears For Fears';

-- [2026-04-05] You Spin Me Round (Like a Record) — Dead Or Alive
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('You Spin Me Round (Like a Record)', 'UK', NULL, 'Synth pop', 195, 'English', '80s');
INSERT INTO artists (name, alias) VALUES ('Dead Or Alive', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'You Spin Me Round (Like a Record)'
)
AND a.name = 'Dead Or Alive';

-- [2026-04-05] 3 Words — Cheryl Cole, will.i.am
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('3 Words', 'UK', NULL, 'Dance pop', 273, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Cheryl Cole', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '3 Words'
)
AND a.name = 'Cheryl Cole';
INSERT INTO artists (name, alias) VALUES ('will.i.am', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = '3 Words'
)
AND a.name = 'will.i.am';
UPDATE songs SET title = '3 Words (feat. will.i.am)' WHERE title = '3 Words';

-- [2026-04-05] Ready for the Weekend — Icona Pop
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Ready for the Weekend', 'UK', NULL, 'Electro house', 162, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Icona Pop', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Ready for the Weekend'
)
AND a.name = 'Icona Pop';

-- [2026-04-05] Sun Goes Down — Icona Pop, The Knocks, St. Lucia
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Sun Goes Down', 'UK', NULL, 'Dance pop', 195, 'English', 'Pop');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sun Goes Down'
)
AND a.name = 'Icona Pop';
INSERT INTO artists (name, alias) VALUES ('The Knocks', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sun Goes Down'
)
AND a.name = 'The Knocks';
INSERT INTO artists (name, alias) VALUES ('St. Lucia', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sun Goes Down'
)
AND a.name = 'St. Lucia';
UPDATE songs SET title = 'Sun Goes Down (feat. The Knocks, St. Lucia)' WHERE title = 'Sun Goes Down';

-- [2026-04-05] Haboglabotribin' — Bernard Wright
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Haboglabotribin''', 'USA', NULL, 'Funk', 259, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('Bernard Wright', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Haboglabotribin'''
)
AND a.name = 'Bernard Wright';

-- [2026-04-05] Rip Off — After School
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Rip Off', 'Korea', NULL, 'Kpop', 177, 'Korean', 'K');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Rip Off'
)
AND a.name = 'After School';

-- [2026-04-05] Happy Days — Brooke Candy
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Happy Days', 'USA', NULL, 'Electro pop', 222, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Brooke Candy', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Happy Days'
)
AND a.name = 'Brooke Candy';

-- [2026-04-05] Destroy Everything You Touch — Ladytron
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Destroy Everything You Touch', 'UK', NULL, 'Electro pop', 276, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Ladytron', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Destroy Everything You Touch'
)
AND a.name = 'Ladytron';

-- [2026-04-05] Good Clean Fun — Clearlake
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Good Clean Fun', 'UK', NULL, 'Indie rock', 234, 'English', 'Pop');
INSERT INTO artists (name, alias) VALUES ('Clearlake', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Good Clean Fun'
)
AND a.name = 'Clearlake';

-- [2026-04-05] Sun Is Shining — Bob Marley, The Wailers
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Sun Is Shining', 'Jamaica', NULL, 'Reggae', 298, 'English', 'Reggae');
INSERT INTO artists (name, alias) VALUES ('Bob Marley', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sun Is Shining'
)
AND a.name = 'Bob Marley';
INSERT INTO artists (name, alias) VALUES ('The Wailers', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Sun Is Shining'
)
AND a.name = 'The Wailers';

-- [2026-04-05] WHISTLE — BLACKPINK
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('WHISTLE', 'Korea', NULL, 'Kpop', 211, 'Korean', 'K');
INSERT INTO artists (name, alias) VALUES ('BLACKPINK', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'WHISTLE'
)
AND a.name = 'BLACKPINK';

-- [2026-04-05] ILYSM — Steve Aoki, Autoerotique
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('ILYSM', 'USA', NULL, 'EDM', 200, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Steve Aoki', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'ILYSM'
)
AND a.name = 'Steve Aoki';
INSERT INTO artists (name, alias) VALUES ('Autoerotique', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'ILYSM'
)
AND a.name = 'Autoerotique';

-- [2026-04-05] Masterplan — The Hacker, Miss Kittin
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Masterplan', 'France', NULL, 'Dance pop', 390, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('The Hacker', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Masterplan'
)
AND a.name = 'The Hacker';
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Masterplan'
)
AND a.name = 'Miss Kittin';
UPDATE songs SET title = 'Masterplan (feat. Miss Kittin)' WHERE title = 'Masterplan';

-- [2026-04-05] Half Bad — White Reaper
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Half Bad', 'USA', NULL, 'Alt rock', 163, 'English', 'Punk');
INSERT INTO artists (name, alias) VALUES ('White Reaper', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Half Bad'
)
AND a.name = 'White Reaper';

-- [2026-04-05] I'd Rather Be with You — Bootsy Collins
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I''d Rather Be with You', 'USA', NULL, 'Funk', 297, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Bootsy Collins', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I''d Rather Be with You'
)
AND a.name = 'Bootsy Collins';

-- [2026-04-05] ALL OF YOU SAY — MINZY
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('ALL OF YOU SAY', 'Korea', NULL, 'Pop', 151, 'English', 'K');
INSERT INTO artists (name, alias) VALUES ('MINZY', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'ALL OF YOU SAY'
)
AND a.name = 'MINZY';

-- [2026-04-05] Keep Up — Hyper Crush
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Keep Up', 'USA', NULL, 'Neon electro', 193, 'English', 'Fx');
INSERT INTO artists (name, alias) VALUES ('Hyper Crush', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Keep Up'
)
AND a.name = 'Hyper Crush';

-- [2026-04-05] Flip the Switch — Hyper Crush
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Flip the Switch', 'USA', NULL, 'Neon electro', 203, 'English', 'Fx');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Flip the Switch'
)
AND a.name = 'Hyper Crush';

-- [2026-04-05] Take Me Back — KaW
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Take Me Back', 'USA', NULL, 'Electronic', 123, 'English', 'IIDX+');
INSERT INTO artists (name, alias) VALUES ('KaW', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Take Me Back'
)
AND a.name = 'KaW';

-- [2026-04-05] Disconnected — Inspector K
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Disconnected', 'USA', NULL, 'Electronic', 121, 'English', 'IIDX+');
INSERT INTO artists (name, alias) VALUES ('Inspector K', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Disconnected'
)
AND a.name = 'Inspector K';

-- [2026-04-05] Infection — Inspector K
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Infection', 'USA', NULL, 'Electronic', 138, 'English', 'IIDX+');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Infection'
)
AND a.name = 'Inspector K';

-- [2026-04-05] Tension — Inspector K
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Tension', 'USA', NULL, 'Electronic', 120, 'English', 'IIDX+');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Tension'
)
AND a.name = 'Inspector K';

-- [2026-04-05] Nóng — BigDaddy, Hạnh Sino
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Nóng', 'Vietnam', 'Nóng', 'V pop', 197, 'Vietnamese', 'Viet');
INSERT INTO artists (name, alias) VALUES ('BigDaddy', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Nóng'
)
AND a.name = 'BigDaddy';
INSERT INTO artists (name, alias) VALUES ('Hạnh Sino', 'Hạnh Sino');
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'featured'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Nóng'
)
AND a.name = 'Hạnh Sino';
UPDATE songs SET title = 'Nóng (feat. Hạnh Sino)' WHERE title = 'Nóng';

-- [2026-04-05] Paralyzed — Agnes Monica
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Paralyzed', 'Indonesia', NULL, 'Pop', 217, 'Indonesian', 'Indo');
INSERT INTO artists (name, alias) VALUES ('Agnes Monica', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Paralyzed'
)
AND a.name = 'Agnes Monica';

-- [2026-04-05] I Feel Love — Donna Summer
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('I Feel Love', 'USA', NULL, 'Disco', 493, 'English', 'Cx');
INSERT INTO artists (name, alias) VALUES ('Donna Summer', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'I Feel Love'
)
AND a.name = 'Donna Summer';

-- [2026-04-05] Give Me the Night — George Benson
INSERT INTO songs (title, country, alias, genre, duration, language, notes) VALUES ('Give Me the Night', 'USA', NULL, 'R&B', 301, 'English', 'Ox');
INSERT INTO artists (name, alias) VALUES ('George Benson', NULL);
INSERT OR IGNORE INTO song_artists (song_id, artist_id, role)
SELECT s.id, a.id, 'primary'
FROM songs s, artists a
WHERE s.rowid = (
    SELECT MAX(rowid) FROM songs WHERE title = 'Give Me the Night'
)
AND a.name = 'George Benson';
