#!/usr/bin/env python3
"""
rebuild_data_sql.py — regenerate data.sql from the current database.

This script reads the entire contents of catalogue.db and writes a fresh
data.sql containing INSERT statements for artists, songs, and song_artists
in a reproducible, ordered format.

Usage:
    python rebuild_data_sql.py
"""

import sqlite3
import os
import sys

DB_FILE = "catalogue.db"
DATA_SQL = "data.sql"

def escape(s):
    if s is None:
        return ""
    return s.replace("'", "''")

def sql_text(s):
    if s is None:
        return "NULL"
    if isinstance(s, str) and s.strip() == "":
        return "NULL"
    return f"'{escape(s)}'"

def main():
    if not os.path.exists(DB_FILE):
        print(f"✗  {DB_FILE} not found.")
        sys.exit(1)

    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()

    print("Rebuilding data.sql from database...")

    with open(DATA_SQL, "w", encoding="utf-8") as f:
        f.write("-- Radio Catalogue data\n")
        f.write("-- Auto-generated by rebuild_data_sql.py\n")
        f.write("PRAGMA foreign_keys = ON;\n\n")

        # -----------------------------
        # Export artists
        # -----------------------------
        cursor.execute("SELECT id, name, alias FROM artists ORDER BY id")
        artists = cursor.fetchall()

        for (artist_id, name, alias) in artists:
            f.write(
                "INSERT INTO artists (name, alias) VALUES "
                f"('{escape(name)}', {sql_text(alias)});\n"
            )

        f.write("\n")

        # -----------------------------
        # Export songs
        # -----------------------------
        cursor.execute("SELECT id, title, alias, country, genre, language, notes FROM songs ORDER BY id")
        songs = cursor.fetchall()

        for (song_id, title, alias, country, genre, language, notes) in songs:
            f.write(
                "INSERT INTO songs (title, genre, language, notes, alias) VALUES "
                f"('{escape(title)}', {sql_text(country)}, {sql_text(genre)}, {sql_text(language)}, "
                f"{sql_text(notes)}, {sql_text(alias)});\n"
            )

        f.write("\n")

        # -----------------------------
        # Export song_artists
        # -----------------------------
        cursor.execute(
            "SELECT song_id, artist_id, role FROM song_artists ORDER BY song_id, artist_id"
        )
        links = cursor.fetchall()

        for (song_id, artist_id, role) in links:
            f.write(
                "INSERT OR IGNORE INTO song_artists (song_id, artist_id, role) "
                f"VALUES ({song_id}, {artist_id}, {sql_text(role)});\n"
            )

    conn.close()
    print(f"✓  data.sql rebuilt successfully.")

if __name__ == "__main__":
    main()